### ISSUE TITLE
unexpected result with ascii value

### ISSUE THREAD

**Issue by kasperk81** [AlanRVA/Homoglyphic#2]
this sample
```c#
// dotnet new console -n homoglyphic-test
// dotnet add homoglyphic-test package Homoglyphic -v 1.0.0

using System;
using Homoglyphic;

var pairs = HomoglyphLoader.LoadPairs("homoglyphs.csv");
var replacer = new HomoglyphReplacer(pairs);

string upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
string upperReplaced = replacer.Replace(upper);

string lower = "abcdefghijklmnopqrstuvwxyz";
string lowerReplaced = replacer.Replace(lower);

Console.WriteLine("{0} {1} {2}", upper, upper == upperReplaced ? "==" : "!=", upperReplaced);
Console.WriteLine("{0} {1} {2}", lower, lower == lowerReplaced ? "==" : "!=", lowerReplaced);
```
outputs
```
ABCDEFGHIJKLMNOPQRSTUVWXYZ != ABCDEFGH1JKLMN0PQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz != abcdefghijk1mn0pqrstuvwxyz
```

**Comment by AlanRVA** [comment]
The project has been re-designed. What I was initially hoping to accomplish (normalizing strings with homoglyphs to their common, English alphabet look-alikes) can't be done without a more complex analysis of the text being processed as there's no easy way to determine how to handle cases where, as you found, an upper-case i or lower-case l could be swapped for the number one and vice versa.

Version 2 instead focuses on providing the library with strings you are looking to find in a given string and it will tell you if there are any matches, with or without, homoglyphs, what the matches are and where they begin in the given string's char index.
